#///////////////////////////////////////////////
#//
#//  This file is part of
#//      ___  ____  __  __  ___    __    ____
#//     / __)(_  _)(  \/  )/ __)  /__\  (  _ \
#//     \__ \ _)(_  )    (( (__  /(__)\  )(_) )
#//     (___/(____)(_/\/\_)\___)(__)(__)(____/
#//
#//  A simulation library for electronic circuits
#//  See also https://github.com/Terstegge/SimCad
#//  (c) Andreas Terstegge
#//
#///////////////////////////////////////////////

SIMCAD_DIR = ../..
BUILD_DIR  = BUILD

TARGET_BIN_FILE = Computer
TARGET_NET_FILE = kicad/8bit-computer.net
TARGET_SRC_DIRS = .
TARGET_INC_DIRS = . kicad

include $(SIMCAD_DIR)/common.mk
