#///////////////////////////////////////////////
#//
#//  This file is part of
#//   ____  ____  ___  ____  ___  ____  __  __
#//  (  _ \(_  _)/ __)(_  _)/ __)(_  _)(  \/  )
#//   )(_) )_)(_( (_-. _)(_ \__ \ _)(_  )    (
#//  (____/(____)\___/(____)(___/(____)(_/\/\_)
#//
#//  (c) 2020  A. Terstegge
#//
#///////////////////////////////////////////////
#//
# 
DIGISIM_DIR = ../..
BUILD_DIR   = BUILD

TARGET_BIN_FILE = RS-flipflop
TARGET_NET_FILE = RS-flipflop.net
TARGET_SRC_DIRS = .
TARGET_INC_DIRS = .

include $(DIGISIM_DIR)/common.mk
