#/////////////////////////////////////////////////
#//
#//  This file is part of
#//      ___  ____  __  __  ___    __    ____
#//     / __)(_  _)(  \/  )/ __)  /__\  (  _ \
#//     \__ \ _)(_  )    (( (__  /(__)\  )(_) )
#//     (___/(____)(_/\/\_)\___)(__)(__)(____/
#//
#//  A simulation library for electronic circuits
#//  See also https://github.com/Terstegge/SimCad
#//  (c) Andreas Terstegge
#//
#/////////////////////////////////////////////////
 
SIMCAD_DIR = ../..
BUILD_DIR  = BUILD

TARGET_BIN_FILE = RS-flipflop
TARGET_NET_FILE = RS-flipflop.net
TARGET_SRC_DIRS = .
TARGET_INC_DIRS = .

include $(SIMCAD_DIR)/common.mk
