#///////////////////////////////////////////////
#//
#//  This file is part of
#//   ____  ____  ___  ____  ___  ____  __  __
#//  (  _ \(_  _)/ __)(_  _)/ __)(_  _)(  \/  )
#//   )(_) )_)(_( (_-. _)(_ \__ \ _)(_  )    (
#//  (____/(____)\___/(____)(___/(____)(_/\/\_)
#//
#//  (c) 2020  A. Terstegge
#//
#///////////////////////////////////////////////
#//
# 
SIMCAD_DIR = ../..
BUILD_DIR  = BUILD

TARGET_BIN_FILE = SimpleNet1
TARGET_NET_FILE = SimpleNet1.net
TARGET_SRC_DIRS = .
TARGET_INC_DIRS = .

include $(SIMCAD_DIR)/common.mk
